# Generated by Django 4.1.7 on 2023-05-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsemployee',
            name='check_review',
            field=models.CharField(choices=[('На проверке', 'На проверке'), ('Одобрен', 'Одобрен'), ('Не уникален', 'Не уникален'), ('Нет статуса', 'Нет статуса')], default='На проверке', max_length=100),
        ),
        migrations.AlterField(
            model_name='reviewsemployee',
            name='global_check_review',
            field=models.CharField(choices=[('На проверке', 'На проверке'), ('Одобрен', 'Одобрен'), ('Не уникален', 'Не уникален'), ('Нет статуса', 'Нет статуса')], default='Нет статуса', max_length=100),
        ),
    ]
