# Generated by Django 4.1.5 on 2023-05-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectors',
            fields=[
                ('pk_Projectors', models.AutoField(primary_key=True, serialize=False, verbose_name='ПК_Проектора')),
                ('inventory_number', models.PositiveIntegerField(verbose_name='Инвент. номер')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('date_service', models.DateField(blank=True, null=True, verbose_name='Дата обслуживания')),
                ('date_repair', models.DateField(blank=True, null=True, verbose_name='Дата ремонта')),
                ('malfunctions', models.TextField(blank=True, null=True, verbose_name='Неисправности')),
                ('location', models.CharField(max_length=25, verbose_name='Месторасположение')),
                ('other', models.CharField(blank=True, max_length=250, null=True, verbose_name='Прочее')),
            ],
            options={
                'verbose_name': 'Проектор',
                'verbose_name_plural': 'Проекторы',
            },
        ),
    ]
